#!/usr/bin/env node
/**
 * optimize-images.js
 * ------------------
 * Reads every image in  images/raw/  and writes responsive, EXIF-stripped
 * derivatives to  images/optimized/ , plus:
 *   - a WebP and a JPEG at each width (640 / 1280 / 1920, never upscaled)
 *   - a tiny blurred LQIP placeholder (inlined into the manifest as a data URI)
 *   - images/manifest.json  with real pixel dimensions so the HTML can set
 *     width/height and avoid layout shift
 *
 * The social link-preview image (images/og-image.jpg) is intentionally
 * hand-cropped to exactly 1200x630 and is NOT generated here, so this script
 * can never regenerate it at the wrong dimensions.
 *
 * You normally never need to touch this file. To add photos, drop them in
 * images/raw/ and run:  npm run optimize
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const RAW_DIR = path.join(ROOT, 'images', 'raw');
const OUT_DIR = path.join(ROOT, 'images', 'optimized');
const MANIFEST = path.join(ROOT, 'images', 'manifest.json');

// Responsive widths. Larger widths are skipped when the source is smaller,
// so images are never upscaled.
const TARGET_WIDTHS = [640, 1280, 1920];

// Quality settings — tuned for photographic content at portfolio scale.
const WEBP_QUALITY = 78;
const JPEG_QUALITY = 82;

const IMAGE_RE = /\.(jpe?g|png|webp|tiff?)$/i;

async function main() {
  if (!fs.existsSync(RAW_DIR)) {
    console.error(`No source folder found at ${RAW_DIR}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const files = fs
    .readdirSync(RAW_DIR)
    .filter((f) => IMAGE_RE.test(f))
    .sort();

  if (files.length === 0) {
    console.error(`No images found in ${RAW_DIR}`);
    process.exit(1);
  }

  console.log(`Optimizing ${files.length} image(s) from images/raw/ …\n`);

  const manifest = {
    generatedAt: new Date().toISOString(),
    note: 'Auto-generated by scripts/optimize-images.js — do not edit by hand.',
    images: {},
  };

  for (const file of files) {
    const slug = file.replace(IMAGE_RE, '');
    const srcPath = path.join(RAW_DIR, file);

    // .rotate() bakes in EXIF orientation before we strip metadata, so
    // portrait shots never come out sideways.
    const base = sharp(srcPath).rotate();
    const meta = await base.metadata();
    const srcWidth = meta.width;
    const srcHeight = meta.height;

    // Pick output widths: every target smaller than the source, capped by the
    // source width itself (so the largest tier is the source, never upscaled).
    const widths = TARGET_WIDTHS.filter((w) => w < srcWidth);
    widths.push(Math.min(srcWidth, Math.max(...TARGET_WIDTHS)));
    const uniqueWidths = [...new Set(widths)].sort((a, b) => a - b);

    for (const w of uniqueWidths) {
      const resized = () => sharp(srcPath).rotate().resize({ width: w });
      await resized()
        .webp({ quality: WEBP_QUALITY })
        .toFile(path.join(OUT_DIR, `${slug}-${w}.webp`));
      await resized()
        .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
        .toFile(path.join(OUT_DIR, `${slug}-${w}.jpg`));
    }

    // Tiny blurred placeholder, inlined so it costs no extra request.
    const lqipBuffer = await sharp(srcPath)
      .rotate()
      .resize({ width: 24 })
      .blur()
      .webp({ quality: 40 })
      .toBuffer();
    const lqip = `data:image/webp;base64,${lqipBuffer.toString('base64')}`;

    manifest.images[slug] = {
      width: srcWidth,
      height: srcHeight,
      aspectRatio: Number((srcWidth / srcHeight).toFixed(4)),
      widths: uniqueWidths,
      lqip,
    };

    console.log(
      `  ${slug.padEnd(16)} ${srcWidth}x${srcHeight}  →  [${uniqueWidths.join(', ')}]`
    );
  }

  fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');

  // Also emit a JS version the page can load with a plain <script> tag, so the
  // site renders even when index.html is opened directly from disk (file://),
  // where fetch() of a local JSON file is blocked.
  const MANIFEST_JS = path.join(ROOT, 'images', 'manifest.js');
  fs.writeFileSync(
    MANIFEST_JS,
    '/* Auto-generated by scripts/optimize-images.js — do not edit by hand. */\n' +
      'window.__MANIFEST__ = ' + JSON.stringify(manifest) + ';\n'
  );

  console.log(`\nWrote ${Object.keys(manifest.images).length} entries to images/manifest.json (+ manifest.js)`);
  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
